name: Nightly CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || format('{0}-{1}', github.ref, github.run_number) }}
  cancel-in-progress: true

jobs:
  CodeCoverage:
    if: always() && github.repository == 'SerenityOS/serenity' && github.ref == 'refs/heads/master'

    strategy:
      fail-fast: false

    uses: ./.github/workflows/serenity-template.yml
    with:
      toolchain: 'Clang'
      os: ubuntu-24.04
      arch: 'x86_64'
      coverage: 'ON'

  LagomGCC:
    if: always() && github.repository == 'SerenityOS/serenity' && github.ref == 'refs/heads/master'

    strategy:
      fail-fast: false

    uses: ./.github/workflows/lagom-template.yml
    with:
      toolchain: 'GNU'
      os_name: 'Linux'
      os: ubuntu-24.04
